apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: seerr

namespace: download

resources:
  - ./resources/deployment.yaml
  - ./resources/http-route.yaml
  - ./resources/pvc-config.yaml
  - ./resources/service.yaml
