apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: radarr

namespace: download

resources:
  - ./resources/deployment.yaml
  - ./resources/http-route.yaml
  - ./resources/namespace.yaml
  - ./resources/pv-download.yaml
  - ./resources/pv-media.yaml
  - ./resources/pvc-config.yaml
  - ./resources/pvc-download.yaml
  - ./resources/pvc-media.yaml
  - ./resources/service.yaml
