apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cnpg

namespace: cnpg-system

helmCharts:
  - name: cnpg
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cloudnative-pg
    namespace: cnpg-system
    version: 0.26.1
    valuesFile: ./values.yaml

resources:
  - ./resources/namespace.yaml
